service: lambot
package:
  exclude:
    - infra/.terraform/**

provider:
  name: aws
  runtime: nodejs8.10
  region: us-east-1
  endpointType: regional
  memorySize: 128
  iamRoleStatements:
    - Effect: Allow
      Action: ecs:RunTask
      Resource:
        - 'Fn::Join':
          - ':'
          -
            - 'arn:aws:ecs'
            - Ref: 'AWS::Region'
            - Ref: 'AWS::AccountId'
            - 'task-definition/lambot-task'
    - Effect: Allow
      Action: iam:PassRole
      Resource:
        - 'Fn::Join':
          - ':'
          -
            - 'arn:aws:iam:'
            - Ref: 'AWS::AccountId'
            - 'role/lambot-ci-ecs-task-exec'

functions:
  webhook:
    handler: index.webhook
    events:
      - http:
          path: webhook
          method: post
          cors: true
